"""People of Acts II and III who appear in more than one chapter (faces and sprites share sheet and index)."""
from story.common import Speaker, npc_speaker

MORI = npc_speaker("Mori Daisuke", "Evil", 1)
KOSAKA = npc_speaker("Kōsaka Tetsuji", "People3", 4)
RIN = npc_speaker("Asahina Rin", "Actor2", 2)      # fights in the party as a guest: masculine look (the player-character rule)
SAKI = npc_speaker("Yukimura Saki", "People2", 3)
NISHIKI = npc_speaker("Nishiki Eiji", "People3", 5)
HERALD = npc_speaker("Herold", "People3", 7)
SOMA = npc_speaker("Takamura Sōma", "Actor3", 0)
HIKARI = npc_speaker("Mizushima Hikari", "Actor1", 7)
HAYATO = npc_speaker("Asahina Hayato", "Actor1", 6)
SHIRANUI = Speaker("Shiranui", "", 0, ("$BigMonster2", 0))
GOEN = npc_speaker("Gōen", "Evil", 3)
YUKINO = npc_speaker("Tsukishiro Yukino", "Actor3", 2)  # joins the party in Act III: masculine look
ROYAL_GUARD = npc_speaker("Königliche Garde", "Actor3", 6)
WALL_SOLDIER = npc_speaker("Wallsoldat", "People3", 6)

# Act III
EMPRESS = npc_speaker("Kaiserin Kujō Sayaka", "People3", 3)
KIYOKO = npc_speaker("Amane Kiyoko", "People2", 5)
TSUMUGI = npc_speaker("Tsumugi", "People2", 1)
KIRISHIMA = npc_speaker("Kirishima Daigo", "People4", 0)
GOKI = npc_speaker("Kanemoto Gōki", "People2", 4)
ARENAMASTER = npc_speaker("Arenameister Ishikawa", "People4", 6)
KAGURA = npc_speaker("Gräfin Kagura Yui", "Nature", 6)
SOTA = npc_speaker("Ōkami Sōta", "Actor2", 4)
NANAMI = npc_speaker("Kitsunezaki Nanami", "Nature", 4)
SHIROGANE = npc_speaker("Shirogane", "Monster", 4)
KUSAKI = npc_speaker("Förster Kusaki", "People1", 6)
IWAKURA = npc_speaker("Iwakura Gōtetsu", "People2", 6)
TSURUGI = npc_speaker("Vorarbeiter Tsurugi", "People4", 4)
MUKURO = npc_speaker("Mukuro", "Evil", 2)
HISA = npc_speaker("Minato Hisa", "People3", 1)
RUI = npc_speaker("Kaizaki Rui", "People4", 5)
SHIGURE = npc_speaker("Shigure", "Actor2", 0)
KAGERO = npc_speaker("Kagerō", "Evil", 4)
TOMA = npc_speaker("Kurenai Tōma", "Actor1", 4)
